package screen;

import java.awt.event.KeyListener;
import javax.swing.*;

public class oldDesign extends javax.swing.JFrame {
    
    //private ClassicMode mode = new ClassicMode();

    /**
     * Creates new form NewJFrame
     */
    public oldDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tile04 = new javax.swing.JLabel();
        tile00 = new javax.swing.JLabel();
        tile01 = new javax.swing.JLabel();
        tile02 = new javax.swing.JLabel();
        tile03 = new javax.swing.JLabel();
        tile14 = new javax.swing.JLabel();
        tile10 = new javax.swing.JLabel();
        tile11 = new javax.swing.JLabel();
        tile12 = new javax.swing.JLabel();
        tile13 = new javax.swing.JLabel();
        tile24 = new javax.swing.JLabel();
        tile20 = new javax.swing.JLabel();
        tile21 = new javax.swing.JLabel();
        tile22 = new javax.swing.JLabel();
        tile23 = new javax.swing.JLabel();
        tile34 = new javax.swing.JLabel();
        tile30 = new javax.swing.JLabel();
        tile31 = new javax.swing.JLabel();
        tile32 = new javax.swing.JLabel();
        tile33 = new javax.swing.JLabel();
        tile44 = new javax.swing.JLabel();
        tile40 = new javax.swing.JLabel();
        tile41 = new javax.swing.JLabel();
        tile42 = new javax.swing.JLabel();
        tile43 = new javax.swing.JLabel();
        tile54 = new javax.swing.JLabel();
        tile50 = new javax.swing.JLabel();
        tile51 = new javax.swing.JLabel();
        tile52 = new javax.swing.JLabel();
        tile53 = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wordle");
        setBounds(new java.awt.Rectangle(20, 20, 20, 20));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        setLocation(new java.awt.Point(960, 540));
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(480, 720));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tile04.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile04.setForeground(new java.awt.Color(0, 0, 0));
        tile04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile04.setToolTipText("");
        tile04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile04, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 50, 50));

        tile00.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile00.setForeground(new java.awt.Color(0, 0, 0));
        tile00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile00.setToolTipText("");
        tile00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tile00.setName("tile00"); // NOI18N
        jPanel1.add(tile00, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 50, 50));

        tile01.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile01.setForeground(new java.awt.Color(0, 0, 0));
        tile01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile01.setToolTipText("");
        tile01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile01, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 50, 50));

        tile02.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile02.setForeground(new java.awt.Color(0, 0, 0));
        tile02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile02.setToolTipText("");
        tile02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile02, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 50, 50));

        tile03.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile03.setForeground(new java.awt.Color(0, 0, 0));
        tile03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile03.setToolTipText("");
        tile03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile03, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 50, 50));

        tile14.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile14.setForeground(new java.awt.Color(0, 0, 0));
        tile14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile14.setToolTipText("");
        tile14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 50, 50));

        tile10.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile10.setForeground(new java.awt.Color(0, 0, 0));
        tile10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile10.setToolTipText("");
        tile10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 50, 50));

        tile11.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile11.setForeground(new java.awt.Color(0, 0, 0));
        tile11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile11.setToolTipText("");
        tile11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 50, 50));

        tile12.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile12.setForeground(new java.awt.Color(0, 0, 0));
        tile12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile12.setToolTipText("");
        tile12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 50, 50));

        tile13.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile13.setForeground(new java.awt.Color(0, 0, 0));
        tile13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile13.setToolTipText("");
        tile13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 50, 50));

        tile24.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile24.setForeground(new java.awt.Color(0, 0, 0));
        tile24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile24.setToolTipText("");
        tile24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 50, 50));

        tile20.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile20.setForeground(new java.awt.Color(0, 0, 0));
        tile20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile20.setToolTipText("");
        tile20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 50, 50));

        tile21.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile21.setForeground(new java.awt.Color(0, 0, 0));
        tile21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile21.setToolTipText("");
        tile21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 50, 50));

        tile22.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile22.setForeground(new java.awt.Color(0, 0, 0));
        tile22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile22.setToolTipText("");
        tile22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 50, 50));

        tile23.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile23.setForeground(new java.awt.Color(0, 0, 0));
        tile23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile23.setToolTipText("");
        tile23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 50, 50));

        tile34.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile34.setForeground(new java.awt.Color(0, 0, 0));
        tile34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile34.setToolTipText("");
        tile34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile34, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 50, 50));

        tile30.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile30.setForeground(new java.awt.Color(0, 0, 0));
        tile30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile30.setToolTipText("");
        tile30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 50, 50));

        tile31.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile31.setForeground(new java.awt.Color(0, 0, 0));
        tile31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile31.setToolTipText("");
        tile31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 50, 50));

        tile32.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile32.setForeground(new java.awt.Color(0, 0, 0));
        tile32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile32.setToolTipText("");
        tile32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 50, 50));

        tile33.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile33.setForeground(new java.awt.Color(0, 0, 0));
        tile33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile33.setToolTipText("");
        tile33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile33, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 50, 50));

        tile44.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile44.setForeground(new java.awt.Color(0, 0, 0));
        tile44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile44.setToolTipText("");
        tile44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile44, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 50, 50));

        tile40.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile40.setForeground(new java.awt.Color(0, 0, 0));
        tile40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile40.setToolTipText("");
        tile40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile40, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 50, 50));

        tile41.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile41.setForeground(new java.awt.Color(0, 0, 0));
        tile41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile41.setToolTipText("");
        tile41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 50, 50));

        tile42.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile42.setForeground(new java.awt.Color(0, 0, 0));
        tile42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile42.setToolTipText("");
        tile42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile42, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 50, 50));

        tile43.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile43.setForeground(new java.awt.Color(0, 0, 0));
        tile43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile43.setToolTipText("");
        tile43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile43, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 50, 50));

        tile54.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile54.setForeground(new java.awt.Color(0, 0, 0));
        tile54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile54.setToolTipText("");
        tile54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile54, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 50, 50));

        tile50.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile50.setForeground(new java.awt.Color(0, 0, 0));
        tile50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile50.setToolTipText("");
        tile50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile50, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 50, 50));

        tile51.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile51.setForeground(new java.awt.Color(0, 0, 0));
        tile51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile51.setToolTipText("");
        tile51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile51, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 50, 50));

        tile52.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile52.setForeground(new java.awt.Color(0, 0, 0));
        tile52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile52.setToolTipText("");
        tile52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile52, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 50, 50));

        tile53.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        tile53.setForeground(new java.awt.Color(0, 0, 0));
        tile53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tile53.setToolTipText("");
        tile53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197), 2));
        tile53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tile53, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 50, 50));

        warningLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(0, 0, 0));
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 480, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        /*warningLabel.setText("");
        if (! mode.isDone()) {
            JLabel[][] tiles = {
                {tile00, tile01, tile02, tile03, tile04},
                {tile10, tile11, tile12, tile13, tile14},
                {tile20, tile21, tile22, tile23, tile24},
                {tile30, tile31, tile32, tile33, tile34},
                {tile40, tile41, tile42, tile43, tile44},
                {tile50, tile51, tile52, tile53, tile54}
            };
            
            String character = evt.getKeyText(evt.getKeyCode());
            System.out.println("Key press: " + evt.getKeyText(evt.getKeyCode()));
            
            if ("ABCDEFGHIJKLMNOPQRSTUVWXYZ".contains(character)) mode.nextTile(character, tiles);
            else if (character.equals("Backspace")) mode.delTile(tiles);
            else if (character.equals("Enter")) {
                if (! mode.isDone() && mode.getCharIndex() == 5 && mode.hasWord(tiles)) {
                    mode.checkTile(tiles);
                } else if (mode.getCharIndex() != 5) {
                    warningLabel.setText("not enough letters");
                } else if (! mode.hasWord(tiles)) {
                    warningLabel.setText("not in word list");
                }
            }
            else System.out.println("That's not key");
        }*/
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oldDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oldDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oldDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oldDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oldDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tile00;
    private javax.swing.JLabel tile01;
    private javax.swing.JLabel tile02;
    private javax.swing.JLabel tile03;
    private javax.swing.JLabel tile04;
    private javax.swing.JLabel tile10;
    private javax.swing.JLabel tile11;
    private javax.swing.JLabel tile12;
    private javax.swing.JLabel tile13;
    private javax.swing.JLabel tile14;
    private javax.swing.JLabel tile20;
    private javax.swing.JLabel tile21;
    private javax.swing.JLabel tile22;
    private javax.swing.JLabel tile23;
    private javax.swing.JLabel tile24;
    private javax.swing.JLabel tile30;
    private javax.swing.JLabel tile31;
    private javax.swing.JLabel tile32;
    private javax.swing.JLabel tile33;
    private javax.swing.JLabel tile34;
    private javax.swing.JLabel tile40;
    private javax.swing.JLabel tile41;
    private javax.swing.JLabel tile42;
    private javax.swing.JLabel tile43;
    private javax.swing.JLabel tile44;
    private javax.swing.JLabel tile50;
    private javax.swing.JLabel tile51;
    private javax.swing.JLabel tile52;
    private javax.swing.JLabel tile53;
    private javax.swing.JLabel tile54;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables

}